services:
  plex:
    image: plexinc/pms-docker:latest

    restart: unless-stopped

    environment:
    - ADVERTISE_IP=$PLEX_IP
    - TZ="America/Chicago"
    - PLEX_CLAIM=$PLEX_CLAIM
    - VERSION=latest

    volumes:
    - ./config:/config
    - ./transcode:/transcode
    - E:/Plex Files:/data

    ports:
    - "32400:32400/tcp"
    - "3005:3005/tcp"
    - "8324:8324/tcp"
    - "32469:32469/tcp"
    - "1900:1900/udp"
    - "32410:32410/udp"
    - "32412:32412/udp"
    - "32413:32413/udp"
    - "32414:32414/udp"

    container_name: plex

    labels:
      CONNECTION_PORT: "32400"
      SERVER_NAME: Plex
      SERVER_TYPE: "Plex: All media"
    
    networks:
      - plex

networks:
  plex:
    external: true